# Generated by Django 5.1.4 on 2026-03-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('fallback', 'Fallback'), ('error', 'Error')], default='ready', max_length=20)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('import_stats', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(db_index=True, max_length=32)),
                ('account_name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, db_index=True, max_length=160, null=True)),
                ('responsible', models.CharField(blank=True, db_index=True, max_length=160, null=True)),
                ('level', models.PositiveSmallIntegerField(db_index=True)),
                ('month_key', models.CharField(db_index=True, max_length=7)),
                ('month_label', models.CharField(max_length=16)),
                ('month_date', models.DateField(db_index=True)),
                ('projected', models.FloatField(default=0)),
                ('executed', models.FloatField(default=0)),
                ('variance_value', models.FloatField(default=0)),
                ('variance_pct', models.FloatField(default=0)),
                ('execution_pct', models.FloatField(default=0)),
                ('is_leaf', models.BooleanField(db_index=True, default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='budget.budgetdataset')),
            ],
            options={
                'ordering': ['month_date', 'account_code'],
                'indexes': [models.Index(fields=['dataset', 'month_date'], name='budget_budg_dataset_120554_idx'), models.Index(fields=['dataset', 'account_code'], name='budget_budg_dataset_e211ce_idx'), models.Index(fields=['dataset', 'area'], name='budget_budg_dataset_ed9777_idx'), models.Index(fields=['dataset', 'responsible'], name='budget_budg_dataset_df3b94_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'account_code', 'account_name', 'area', 'responsible', 'level', 'month_key'), name='budget_entry_unique_row')],
            },
        ),
    ]
